### ISSUE TITLE
Configurable password type

### ISSUE THREAD

**Issue by anupam-git** [pico-wizard/pico-wizard#13]
Define a new configuration entry to set the password type to Pin/Alphanumeric
  - `PASSWORD_TYPE=digitsonly`
  - `PASSWORD_TYPE=alphanumeric` [Default]

**Comment by Strit** [comment]
Does this mean we can provide a config file, to get password to also accept letters, if we use pico-wizard on other devices?

**Comment by anupam-git** [comment]
> Does this mean we can provide a config file, to get password to also accept letters, if we use pico-wizard on other devices?

Yes. 

For reference, right now for plamo it is explicitly set to have `digitsonly` : https://gitlab.manjaro.org/manjaro-arm/packages/community/plasma-mobile/pico-wizard-git/-/blob/master/pico-wizard.conf

You need to set the `PASSWORD_TYPE` parameter to `alphanumeric` or `digitsonly` in `/etc/pico-wizard/pico-wizard.conf`

**Comment by Strit** [comment]
Nice. thanks. :smiley:
