### ISSUE TITLE
Icons should be not SVG on the pinephone

### ISSUE THREAD

**Issue by hphilm** [pico-wizard/pico-wizard#17]
The graphics drivers on a Pinephone render glitches into SVG icons for some reason. We might either improve or use other pictures like PNG in that case.

**Comment by bhush9** [comment]
Hm given like almost 90% of Plasma UI is svg, svg itself might not be broken... Do you have specific example of what is broken?

**Comment by hphilm** [comment]
Here is a screenshot! It renders fine on desktop, but on pinephone it has a distorted background somehow.

<img src="https://user-images.githubusercontent.com/5050022/107939441-ffa16480-6f86-11eb-829b-ad09368176bd.png" height="680">

**Comment by bhush9** [comment]
CC: @notmart any idea?

**Comment by hphilm** [comment]
Marco Martin, [15.02.21 15:37]
(our svg graphics is done in sofware, rendered to qimage and the qimage cached on disk)

**Comment by anupam-git** [comment]
Mistakenly added `ColorOverlay` on top of `Kirigami.Icon` which was causing some rendering issues. Now icon color is set using the `Kirigami.Icon.color` property.

Initial testing shows images are rendering correctly now on pinephone.
