### ISSUE TITLE
Create user with no password

### ISSUE THREAD

**Issue by anupam-git** [pico-wizard/pico-wizard#2]
Suggested by @fkardame :

Some users doesn't want to create a password.
Adapt the user module to create an user without any password

**Comment by hphilm** [comment]
this would disable the lockscreen password at some point. for now we have to add always a numeric password for plasma-mobile.

**Comment by anupam-git** [comment]
> this would disable the lockscreen password at some point. for now we have to add always a numeric password for plasma-mobile.

There is already an issue to track the feature : #13
