### ISSUE TITLE
Does not seem to restart sddm-git properly

### ISSUE THREAD

**Issue by Strit** [pico-wizard/pico-wizard#29]
On the [dev images](https://github.com/manjaro-pinephone/plasma-mobile-dev/releases), I have noticed for a while, that Pico-Wizard is no longer able to restart sddm and have it autologin to the new user. Probably since the switch to using sddm from git master instead of the release version.
This is not an issue on the regular images, so I thing something has changed in sddm git master, that would require some tweaking in pico-wizard to get this working again.

What happens is, that when pico-wizard setup is done, it tried to restart sddm. This fails for some reason, so we just get a blinking cursor in the corner. However, rebooting the device makes it work, so there is nothing wrong with the configs.

**Comment by hphilm** [comment]
Can we do a **git-bisect** on this?

**Comment by hphilm** [comment]
see also here: https://github.com/sddm/sddm/pull/1449

**Comment by Strit** [comment]
This seems to be fixed from SDDM side.
