### ISSUE TITLE
Implement language module

### ISSUE THREAD

**Issue by anupam-git** [pico-wizard/pico-wizard#4]
Implement Language module to generate selected locales

**Comment by Strit** [comment]
When adding the `Locale,` to the config, I get an error stating `Failed to write localegen config` when I try it in the wizard.

Something special needed on the filesystem for this?

**Comment by anupam-git** [comment]
Nothing special should be needed 🤔 
Can you please post the output of this `journalctl SYSLOG_IDENTIFIER=pico-wizard`?

**Comment by Strit** [comment]
I get "no entries" when run on the booted phone after the install is done.

**Comment by Strit** [comment]
Here it is.

[log.log](https://github.com/pico-wizard/pico-wizard/files/6243099/log.log)

It has 3 errors, because I tried 3 different locales.

**Comment by anupam-git** [comment]
@Strit Pushed a fix and updated the manjaro package repo for a new build : https://gitlab.manjaro.org/manjaro-arm/packages/community/plasma-mobile/pico-wizard-git/-/commit/ca9d2b1964d2ebbdadba7981750403635a0d1a07

**Comment by Strit** [comment]
> @Strit Pushed a fix and updated the manjaro package repo for a new build : https://gitlab.manjaro.org/manjaro-arm/packages/community/plasma-mobile/pico-wizard-git/-/commit/ca9d2b1964d2ebbdadba7981750403635a0d1a07

Will test it locally and then push the package to the repo if it works.
Thanks.

**Comment by Strit** [comment]
That made it wizard page work.
But the locale is not applied correctly to the system.
`localectl` still says en_US.UTF-8 (even though it's not what I chose), even after a reboot.

**Comment by anupam-git** [comment]
The module just generates the locales.
I need to set the default locale it seems. 

The current list is a multi selectable option and we need to let the user select the locale and keyboard.
How do you suggest it should be done? 

I am thinking to create a new module after locales to let the user select default locale and the keyboard layout. I am open to any other ideas too.

**Comment by Strit** [comment]
Ah okay. So it's function is not yet to actually set the locales, but just to generate them.

We can install `glibc-locales` package (like we do in Phosh), which already has all the locales built, then pico-wizard should just set the locale.

**Comment by anupam-git** [comment]
So in that case we need a new module to set the locale and keyboard layout. I'll keep this module if some other project needs it in the future.
